### ISSUE TITLE
Chapter7-implementation/part1-2-direct-gateway; Error while starting

### ISSUE THREAD

**Issue by chauhanshubham-dev** [webofthings/wot-book#14]
Hello, 
I wanted to seek some help, in order to get things started for chapter 7, part1-2-direct-gateway nodejs server. 
Till now what I get is (after installing some npm packages which it prompted were missing)

```
$ node wot-server.js
Simulated Passive Infrared sensor started!
/home/pi/Desktop/wot-book/chapter7-implementation/part1-2-direct-gateway/plugins/internal/ledsPlugin.js:32
  Object.observe(what, function (changes) {
         ^

TypeError: Object.observe is not a function
    at observe (/home/pi/Desktop/wot-book/chapter7-implementation/part1-2-direct-gateway/plugins/internal/ledsPlugin.js:32:10)
    at Object.exports.start (/home/pi/Desktop/wot-book/chapter7-implementation/part1-2-direct-gateway/plugins/internal/ledsPlugin.js:13:3)
    at Object.<anonymous> (/home/pi/Desktop/wot-book/chapter7-implementation/part1-2-direct-gateway/wot-server.js:14:12)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
```

The thing worth noting is, the problem seems to be for the ledsPlugin particularly. When I comment the following line in wot-server.js

```
ledsPlugin.start({'simulate': true, 'frequency': 10000}); //#B
```

It seems to run perfectly!

```
$ node wot-server.js
Simulated Passive Infrared sensor started!
Simulated Temperature & Humidity sensor started!
HTTP server started...
WebSocket server started...
Your WoT Pi is up and running on port 8484
not anymore!
there is someone!
not anymore!
there is someone!
not anymore!
Temperature: 38 C, humidity 80 %
there is someone!
```

**Comment by domguinard** [comment]
Hi, yes this is a known issue that appears if you use a version of Node >4.X as the Object.observe() core function was removed from Node (a bummer!)

We are working on a patch for Node >4.X but for now I'd suggest you stick with the official Node LTS (Long Term Support) as suggested in the book (currently 4.5.0 see https://nodejs.org/en/).

**Comment by kjc0** [comment]
The current official Node LTS version is 6.9.1. Any chance of someone applying a fix for this problem?
